"""Workflow runner — walks an action's `steps` list for one work ticket.

`step:` entries dispatch to the orchestrator via ComputeBackendClient
(HTTP). `action:` entries dispatch to LIBRARY in-process — no HTTP hop.
Status transitions declared in YAML are PATCHed before each entry that
declares one. Workflow-level success/failure transitions wrap the run.

Lives in the control plane: direct DB access for work_ticket / action /
reference rows is legitimate here. The orchestrator is reduced to its
SLURM-driver role behind `POST /step/*`.

Workspace contract: each entry runs against a per-attempt subdir
`<work_ticket_workspace_root>/<work_ticket_idx>/<entry-name>/attempt-<N>/`
minted by `_run_entry_with_retry`. The nesting gives two properties at
once — retries (and re-runs) land in fresh dirs (the verifier's "every file
in $output_path must be in manifest" gate stays clean), and prior attempts
persist on disk for postmortem. An entry RE-RUN whose progress row was
deliberately dropped (a `/run` redrive, or `update-lane` invalidating a
completed prep row) skips past its now-orphaned attempt dir to a fresh one
rather than reusing it: the prior output is known-bad and its read-only files
would block the re-run, and the runner cannot delete that dir — a container
step's output is owned by the SLURM job user with read-only (0550) dirs the
control-plane process can neither unlink nor chmod (see `_attempt_is_unowned`).
Entries see each other's outputs via the runner's binding map, which carries
absolute paths forward so consumers don't need to know the producer's attempt
number.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
from datetime import timedelta
from pathlib import Path
from typing import Any

import asyncpg
from qiita_common.actions import (
    ActionCeiling,
    ActionDefinition,
    FlatBaselineResources,
    WorkflowAction,
    WorkflowStep,
)
from qiita_common.api_paths import (
    LibraryPrimitive,
    compute_reads_staging_path,
    compute_upload_staging_path,
)
from qiita_common.backend_failure import BackendFailure, FailureKind, StepNoData
from qiita_common.compute_backend_client import ComputeBackendClient
from qiita_common.models import (
    HOST_FILTER_INDEX_TYPE_MINIMAP2,
    HOST_FILTER_INDEX_TYPE_RYPE,
    ComputeTarget,
    FailureType,
    FoundJobWire,
    ReferenceStatus,
    ScopeTargetKind,
    StepBaselineResources,
    StepHandleWire,
    StepPlanResponse,
    StepProgressState,
    StepStatus,
    StepStatusWire,
    UploadStatus,
    WorkTicketFailureStage,
    WorkTicketState,
)

from .. import step_progress
from ..actions.library import LIBRARY, MINT_FEATURES_OUTPUT_BASENAME
from ..actions.reference import (
    IllegalStatusTransition,
    ReferenceNotFound,
    transition_reference_status,
)
from ..auth.tickets import sign_action, sign_ticket
from ..repositories.block import fetch_block_members
from ..repositories.mask_definition import mint_mask_definition
from ._base import (
    _INFRA_RETRY_BACKOFF_CAP_SECONDS,
    _INFRA_UNREACHABLE_KINDS,
    _PATH_SUFFIX,
    _POLL_DB_READ_BACKOFF_SECONDS,
    _POLL_DB_READ_MAX_ATTEMPTS,
    _POLL_DB_READ_TIMEOUT_SECONDS,
    _STEP_POLL_INTERVAL_SECONDS,
    _TERMINAL_WORK_TICKET_STATES,
    _TRANSIENT_DB_ERRORS,
    _UPLOAD_IDX_SUFFIX,
    WorkflowAborted,
    _clear_transient_retry,
    _infra_backoff_delay,
    _infra_retry_wait,
    _is_transient_db_error,
    _log,
    _note_transient_retry,
    _raise_if_ticket_terminal,
)
from ._db import (
    _ACTION_COLS,
    _NON_TERMINAL_STATES,
    _WORK_TICKET_COLS,
    _WORK_TICKET_FROM,
    _atomic_transition,
    _bump_retry_and_requeue,
    _fetch_action,
    _fetch_work_ticket,
    _guarded_state_update,
    _retry_count,
    _safe_entry_name,
    _transition_to_failed,
    _transition_to_no_data,
    _transition_to_processing_for_resume,
)
from ._dispatch import (
    _OOM_MEMORY_GROWTH,
    _TIMEOUT_WALLTIME_GROWTH,
    _adopt_or_submit,
    _advance_completed_step_status,
    _assert_within_ceiling,
    _best_effort_record_failed,
    _bind_step_inputs,
    _build_scope_target,
    _ceiling_exhausted_failure,
    _current_resource_status,
    _dispatch_step,
    _escalated_mem_floor_after_oom,
    _escalated_walltime_after_timeout,
    _fetch_plan_hint,
    _find_existing_job,
    _patch_resource_status,
    _poll_until_terminal,
    _resolve_baseline_for_step,
    _result_with_infra_retry,
    _shard_fanout_owns_finalize,
)
from ._mask import (
    _QC_RESOLVED_FILTER_TAIL,
    _QC_RESOLVED_MIN_LENGTH,
    ALIGNMENT_IDX_BINDING,
    MASK_IDX_BINDING,
    _adapter_set_hash,
    _build_mask_params,
    _materialize_backfill_adapter_set_hash,
    _mint_read_mask,
    _persist_mask_idx,
    _workflow_needs_mask,
)
from ._processing import (
    PROCESSING_IDX_BINDING,
    _mint_processing_idx,
    _workflow_needs_processing,
)
from ._read_ingest import (
    READS_STAGING_ROOT_BINDING,
    ROUTER_PENDING_BINDING,
    SAMPLE_MAP_BINDING,
    SHARD_FEATURES_BINDING,
    SHARD_ID_BINDING,
    SHARD_MAPPING_BINDING,
    STAGED_MASKED_READS_BINDING,
    STAGED_READS_BINDING,
    _REFERENCE_SEQUENCES_TABLE,
    _do_action_export,
    _do_action_export_read,
    _do_action_export_read_block,
    _do_action_export_read_masked_block,
    _do_get_reference_sequences_roster,
    _resolve_sample_map,
    _resolve_staged_masked_reads,
    _resolve_staged_masked_reads_block,
    _resolve_staged_reads,
    _resolve_staged_reads_block,
    _stage_shard_mapping,
    _stage_shard_roster,
    _stream_masked_reads_to_fastq,
    _workflow_declares_input,
    _workflow_needs_staged_masked_reads,
    _workflow_needs_staged_reads,
    _write_empty_reads_parquet,
    _write_sample_map_parquet,
    _write_shard_mapping_parquet,
)
from ._reconstruct import (
    _attempt_is_unowned,
    _completed_progress_row,
    _dispatch_action,
    _reconstruct_action_outputs,
    _reconstruct_completed_outputs,
    _reconstruct_plan_shards_outputs,
    _run_action_primitive,
)
from ._reference import (
    _REFERENCE_CHUNKS_TABLE,
    _SHARD_ALIGNER_INDEX_TYPE,
    _SHARD_ALIGNER_ROOT_PARENT_DEPTH,
    QC_ADAPTER_BINDING,
    ROUTER_INDEX_PATH_BINDING,
    SHARD_DIRECTORY_BINDING,
    ReferenceIndexNotBuilt,
    _coerce_reference_idx,
    _do_get_reference_sequence_chunks,
    _resolve_host_filter_indexes,
    _resolve_host_filter_legacy,
    _resolve_host_filter_two_reference,
    _resolve_qc_adapters,
    _resolve_reference_index_path,
    _resolve_required_host_index,
    _resolve_sharded_align_index_bindings,
    _resolve_sharded_align_indexes,
    _workflow_needs_adapters,
    _workflow_needs_sharded_align_indexes,
    _write_adapter_parquet,
)
from ._upload import (
    _consume_upload_handles,
    _resolve_upload_handles,
    _submission_bad_input,
)
from ._workflow import (
    _run_entry_with_retry,
    run_workflow,
)

__all__: list[str] = [
    "ActionCeiling",
    "ActionDefinition",
    "Any",
    "BackendFailure",
    "ComputeBackendClient",
    "ComputeTarget",
    "FailureKind",
    "FailureType",
    "FlatBaselineResources",
    "FoundJobWire",
    "HOST_FILTER_INDEX_TYPE_MINIMAP2",
    "HOST_FILTER_INDEX_TYPE_RYPE",
    "IllegalStatusTransition",
    "LIBRARY",
    "LibraryPrimitive",
    "PROCESSING_IDX_BINDING",
    "MASK_IDX_BINDING",
    "MINT_FEATURES_OUTPUT_BASENAME",
    "Path",
    "QC_ADAPTER_BINDING",
    "READS_STAGING_ROOT_BINDING",
    "ReferenceIndexNotBuilt",
    "ReferenceNotFound",
    "ReferenceStatus",
    "SAMPLE_MAP_BINDING",
    "STAGED_MASKED_READS_BINDING",
    "STAGED_READS_BINDING",
    "ScopeTargetKind",
    "StepBaselineResources",
    "StepHandleWire",
    "StepNoData",
    "StepPlanResponse",
    "StepProgressState",
    "StepStatus",
    "StepStatusWire",
    "UploadStatus",
    "WorkTicketFailureStage",
    "WorkTicketState",
    "WorkflowAborted",
    "WorkflowAction",
    "WorkflowStep",
    "_ACTION_COLS",
    "_INFRA_RETRY_BACKOFF_CAP_SECONDS",
    "_INFRA_UNREACHABLE_KINDS",
    "_NON_TERMINAL_STATES",
    "_OOM_MEMORY_GROWTH",
    "_PATH_SUFFIX",
    "_POLL_DB_READ_BACKOFF_SECONDS",
    "_POLL_DB_READ_MAX_ATTEMPTS",
    "_POLL_DB_READ_TIMEOUT_SECONDS",
    "_QC_RESOLVED_FILTER_TAIL",
    "_QC_RESOLVED_MIN_LENGTH",
    "_REFERENCE_CHUNKS_TABLE",
    "_STEP_POLL_INTERVAL_SECONDS",
    "_TERMINAL_WORK_TICKET_STATES",
    "_TIMEOUT_WALLTIME_GROWTH",
    "_TRANSIENT_DB_ERRORS",
    "_UPLOAD_IDX_SUFFIX",
    "_WORK_TICKET_COLS",
    "_WORK_TICKET_FROM",
    "_adapter_set_hash",
    "_adopt_or_submit",
    "_advance_completed_step_status",
    "_assert_within_ceiling",
    "_atomic_transition",
    "_attempt_is_unowned",
    "_best_effort_record_failed",
    "_bind_step_inputs",
    "_build_mask_params",
    "_build_scope_target",
    "_bump_retry_and_requeue",
    "_ceiling_exhausted_failure",
    "_clear_transient_retry",
    "_coerce_reference_idx",
    "_completed_progress_row",
    "_consume_upload_handles",
    "_current_resource_status",
    "_dispatch_action",
    "_dispatch_step",
    "_do_action_export",
    "_do_action_export_read",
    "_do_action_export_read_block",
    "_stream_masked_reads_to_fastq",
    "_do_get_reference_sequence_chunks",
    "_escalated_mem_floor_after_oom",
    "_escalated_walltime_after_timeout",
    "_fetch_action",
    "_fetch_plan_hint",
    "_fetch_work_ticket",
    "_find_existing_job",
    "_guarded_state_update",
    "_infra_backoff_delay",
    "_infra_retry_wait",
    "_is_transient_db_error",
    "_log",
    "_materialize_backfill_adapter_set_hash",
    "_mint_read_mask",
    "_mint_processing_idx",
    "_note_transient_retry",
    "_patch_resource_status",
    "_persist_mask_idx",
    "_poll_until_terminal",
    "_raise_if_ticket_terminal",
    "_reconstruct_action_outputs",
    "_reconstruct_completed_outputs",
    "_resolve_baseline_for_step",
    "_resolve_host_filter_indexes",
    "_resolve_host_filter_legacy",
    "_resolve_host_filter_two_reference",
    "_resolve_qc_adapters",
    "_resolve_reference_index_path",
    "_resolve_required_host_index",
    "_resolve_sample_map",
    "_resolve_staged_masked_reads",
    "_resolve_staged_reads",
    "_resolve_staged_reads_block",
    "_resolve_upload_handles",
    "_result_with_infra_retry",
    "_retry_count",
    "_run_action_primitive",
    "_run_entry_with_retry",
    "_safe_entry_name",
    "_submission_bad_input",
    "_transition_to_failed",
    "_transition_to_no_data",
    "_transition_to_processing_for_resume",
    "_workflow_declares_input",
    "_workflow_needs_adapters",
    "_workflow_needs_mask",
    "_workflow_needs_processing",
    "_workflow_needs_staged_masked_reads",
    "_workflow_needs_staged_reads",
    "_write_adapter_parquet",
    "_write_sample_map_parquet",
    "ALIGNMENT_IDX_BINDING",
    "ROUTER_INDEX_PATH_BINDING",
    "ROUTER_PENDING_BINDING",
    "SHARD_DIRECTORY_BINDING",
    "SHARD_FEATURES_BINDING",
    "SHARD_ID_BINDING",
    "SHARD_MAPPING_BINDING",
    "_REFERENCE_SEQUENCES_TABLE",
    "_SHARD_ALIGNER_INDEX_TYPE",
    "_SHARD_ALIGNER_ROOT_PARENT_DEPTH",
    "_do_action_export_read_masked_block",
    "_do_get_reference_sequences_roster",
    "_reconstruct_plan_shards_outputs",
    "_resolve_sharded_align_index_bindings",
    "_resolve_sharded_align_indexes",
    "_resolve_staged_masked_reads_block",
    "_shard_fanout_owns_finalize",
    "_stage_shard_mapping",
    "_stage_shard_roster",
    "_workflow_needs_sharded_align_indexes",
    "_write_empty_reads_parquet",
    "_write_shard_mapping_parquet",
    "asyncio",
    "asyncpg",
    "compute_reads_staging_path",
    "compute_upload_staging_path",
    "fetch_block_members",
    "hashlib",
    "json",
    "logging",
    "mint_mask_definition",
    "run_workflow",
    "sign_action",
    "sign_ticket",
    "step_progress",
    "timedelta",
    "transition_reference_status",
]
