"""Integration tests for POST and GET /api/v1/sequencing-run.

POST: exercises the wet_lab_admin and system_admin happy paths plus a
regular-user happy path (no system_role gate on this route — the USER
ceiling covers prep_sample:write and run creation carries no further
auth), the scope guard, anonymous 401, Pydantic body validation, and
the find-or-create idempotency surface on the instrument_run_id natural
key: same key + matching payload returns 200 with the existing idx;
same key + mismatching payload returns 409 with a structured
PayloadMismatch detail; supplied-None on retry is ignored.

GET /{idx}: the run-metadata read `submit-host-filter-pool` uses to forward
instrument_model — happy path (incl. null instrument_model + decoded JSONB),
404 on miss, and the read gate (anonymous 401, regular-user 403; same
prep_sample:read + wet_lab_admin gate as the pool roster route).
"""

import json

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from qiita_common.api_paths import URL_SEQUENCING_RUN_LOOKUP_BY_INSTRUMENT_RUN_ID
from qiita_common.auth_constants import API_PREFIX

from qiita_control_plane.main import app

from .conftest import delete_idxs, unique_instrument_id

pytestmark = pytest.mark.db


_ROUTE = f"{API_PREFIX}/sequencing-run"


# ---------------------------------------------------------------------------
# FK-reverse cleanup
# ---------------------------------------------------------------------------


async def _cleanup_tracked(pool, created: dict) -> None:
    """Drop every row tracked in `created` in FK-reverse order.

    Only sequencing_run is tracked at this layer; downstream rows
    (sequenced_pool, sequenced_sample, prep_sample, metadata) are seeded
    and torn down inside their own test files' _cleanup_tracked.
    """
    await delete_idxs(pool, "sequencing_run", created["sequencing_run"])


@pytest_asyncio.fixture
async def ctx(role_keyed_clients):
    """Per-test fixture: route-keyed AsyncClient triple plus a `created`
    tracker for FK-reverse teardown."""
    created: dict = {"sequencing_run": []}
    yield {**role_keyed_clients, "created": created}
    await _cleanup_tracked(role_keyed_clients["pool"], created)


# ---------------------------------------------------------------------------
# Route-call helper
# ---------------------------------------------------------------------------


async def _post_run(client, ctx, **body):
    """POST the route and, on 201, track the created sequencing_run idx for
    FK-reverse cleanup. 200 (find-or-create reuse) returns the same idx
    already tracked from the first 201, so we only track on create."""
    resp = await client.post(_ROUTE, json=body)
    if resp.status_code == 201:
        ctx["created"]["sequencing_run"].append(resp.json()["sequencing_run_idx"])
    return resp


# ===========================================================================
# Happy paths
# ===========================================================================


async def test_create_sequencing_run_wet_lab_admin_minimal(ctx):
    # Wet_lab_admin caller posts the minimum-required body; the route
    # mints a sequencing_run row and returns its idx.
    resp = await _post_run(
        ctx["wet"],
        ctx,
        instrument_run_id=unique_instrument_id("WET"),
        platform="illumina",
    )
    assert resp.status_code == 201, resp.text
    rj = resp.json()
    expected = {
        # Auto-generated by the DB; copy actual into expected so the
        # equality confirms field presence without pinning the idx value.
        "sequencing_run_idx": rj["sequencing_run_idx"],
    }
    assert rj == expected

    # Verify the row landed with the caller's principal_idx as creator and
    # the platform persisted as the enum value.
    row = await ctx["pool"].fetchrow(
        "SELECT instrument_run_id, platform, created_by_idx,"
        " instrument_model, instrument_serial, run_performed_at, extra_metadata"
        " FROM qiita.sequencing_run WHERE idx = $1",
        rj["sequencing_run_idx"],
    )
    actual = dict(row)
    expected = {
        # Auto-generated by the test helper; copy actual into expected so
        # the equality confirms field presence without pinning the value.
        "instrument_run_id": actual["instrument_run_id"],
        "platform": "illumina",
        "created_by_idx": ctx["wet_session"]["principal_idx"],
        "instrument_model": None,
        "instrument_serial": None,
        "run_performed_at": None,
        "extra_metadata": None,
    }
    assert actual == expected


async def test_create_sequencing_run_system_admin_all_fields(ctx):
    # System_admin caller posts every settable column; the route persists
    # all of them.
    instrument_run_id = unique_instrument_id("ADM")
    resp = await _post_run(
        ctx["admin"],
        ctx,
        instrument_run_id=instrument_run_id,
        platform="pacbio_smrt",
        instrument_model="NovaSeq X+",
        instrument_serial="LH00123",
        run_performed_at="2026-04-01T12:00:00Z",
        extra_metadata={"lane_count": 2, "flowcell": "FC-A"},
    )
    assert resp.status_code == 201, resp.text

    row = await ctx["pool"].fetchrow(
        "SELECT instrument_run_id, platform, instrument_model, instrument_serial,"
        " run_performed_at, extra_metadata"
        " FROM qiita.sequencing_run WHERE idx = $1",
        resp.json()["sequencing_run_idx"],
    )
    # asyncpg returns JSONB as a JSON string by default; decode in-place so
    # the dict equality compares structured payloads.
    actual = dict(row)
    actual["extra_metadata"] = json.loads(actual["extra_metadata"])
    expected = {
        "instrument_run_id": instrument_run_id,
        "platform": "pacbio_smrt",
        "instrument_model": "NovaSeq X+",
        "instrument_serial": "LH00123",
        # TIMESTAMPTZ comes back as a tz-aware datetime; copy actual since
        # this assertion only verifies the column was populated.
        "run_performed_at": actual["run_performed_at"],
        "extra_metadata": {"flowcell": "FC-A", "lane_count": 2},
    }
    assert actual == expected


# ===========================================================================
# Auth / scope / role guards
# ===========================================================================


async def test_create_sequencing_run_anonymous_401(ctx):
    # No Authorization header → require_complete_profile chain raises 401.
    app.state.pool = ctx["pool"]
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as anon:
        resp = await anon.post(
            _ROUTE,
            json={
                "instrument_run_id": unique_instrument_id("ANON"),
                "platform": "illumina",
            },
        )
    assert resp.status_code == 401


async def test_create_sequencing_run_missing_scope_403(ctx, no_prep_sample_write_client):
    # PAT omits Scope.PREP_SAMPLE_WRITE → require_scope rejects 403 before
    # the role check runs.
    resp = await no_prep_sample_write_client.post(
        _ROUTE,
        json={
            "instrument_run_id": unique_instrument_id("NOSCOPE"),
            "platform": "illumina",
        },
    )
    assert resp.status_code == 403
    assert "prep_sample:write" in resp.json()["detail"]


async def test_create_sequencing_run_regular_user_passes(ctx):
    # Regular user (system_role=user) using their session-fixture
    # OIDC-resolved token: prep_sample:write is now part of the USER role
    # ceiling, and the route no longer composes require_role_at_least —
    # so a vanilla user can stand up a run. Downstream pool / sample
    # routes enforce caller-creator semantics from this point on.
    resp = await _post_run(
        ctx["user"],
        ctx,
        instrument_run_id=unique_instrument_id("USER"),
        platform="illumina",
    )
    assert resp.status_code == 201, resp.text
    # Pin caller-creator semantics for the downstream pool/sample routes:
    # the resulting run's created_by_idx equals the regular-user principal,
    # so a subsequent pool POST by this user satisfies require_caller_owns_run.
    created_by = await ctx["pool"].fetchval(
        "SELECT created_by_idx FROM qiita.sequencing_run WHERE idx = $1",
        resp.json()["sequencing_run_idx"],
    )
    assert created_by == ctx["user_session"]["principal_idx"]


# ===========================================================================
# Body validation
# ===========================================================================


async def test_create_sequencing_run_missing_required_field_422(ctx):
    # Pydantic validation rejects {} because instrument_run_id and platform
    # are both required.
    resp = await ctx["wet"].post(_ROUTE, json={})
    assert resp.status_code == 422
    missing_locs = {tuple(err["loc"]) for err in resp.json()["detail"]}
    assert ("body", "instrument_run_id") in missing_locs
    assert ("body", "platform") in missing_locs


async def test_create_sequencing_run_invalid_platform_422(ctx):
    # The Platform StrEnum rejects values outside the closed set.
    resp = await ctx["wet"].post(
        _ROUTE,
        json={
            "instrument_run_id": unique_instrument_id("BADP"),
            "platform": "nanopore",
        },
    )
    assert resp.status_code == 422


async def test_create_sequencing_run_empty_instrument_run_id_422(ctx):
    # Pydantic min_length=1 rejects an empty string.
    resp = await ctx["wet"].post(
        _ROUTE,
        json={"instrument_run_id": "", "platform": "illumina"},
    )
    assert resp.status_code == 422


async def test_create_sequencing_run_extra_field_422(ctx):
    # The request model carries extra="forbid"; an unknown field is rejected
    # at the Pydantic boundary rather than silently dropped.
    resp = await ctx["wet"].post(
        _ROUTE,
        json={
            "instrument_run_id": unique_instrument_id("XTRA"),
            "platform": "illumina",
            "not_a_real_column": "x",
        },
    )
    assert resp.status_code == 422


# ===========================================================================
# Constraint mapping
# ===========================================================================


async def test_create_sequencing_run_find_or_create_same_payload_returns_200(ctx):
    # Find-or-create read-through: a second POST with the same
    # instrument_run_id and matching fields returns 200 with the existing
    # idx instead of 409. Required so the bundled qiita submit-bcl-convert
    # CLI's three POSTs converge on retry without operator cleanup.
    instrument_run_id = unique_instrument_id("DUP")
    r1 = await _post_run(
        ctx["wet"],
        ctx,
        instrument_run_id=instrument_run_id,
        platform="illumina",
        instrument_model="NovaSeq X+",
    )
    assert r1.status_code == 201, r1.text
    first_idx = r1.json()["sequencing_run_idx"]

    r2 = await _post_run(
        ctx["wet"],
        ctx,
        instrument_run_id=instrument_run_id,
        platform="illumina",
        instrument_model="NovaSeq X+",
    )
    assert r2.status_code == 200, r2.text
    assert r2.json()["sequencing_run_idx"] == first_idx


async def test_create_sequencing_run_payload_mismatch_returns_409(ctx):
    # Same instrument_run_id + a non-None supplied field disagrees with the
    # stored value → 409 with structured PayloadMismatch detail naming the
    # conflicting field and both values. CLI uses this to refuse to silently
    # mutate a row the operator may have re-bound the wrong way.
    instrument_run_id = unique_instrument_id("MISMATCH")
    r1 = await _post_run(
        ctx["wet"],
        ctx,
        instrument_run_id=instrument_run_id,
        platform="illumina",
        instrument_model="NovaSeq X+",
    )
    assert r1.status_code == 201, r1.text

    r2 = await _post_run(
        ctx["wet"],
        ctx,
        instrument_run_id=instrument_run_id,
        platform="illumina",
        instrument_model="iSeq",
    )
    assert r2.status_code == 409, r2.text
    detail = r2.json()["detail"]
    expected = {
        "conflicting_field": "instrument_model",
        "existing_value": "NovaSeq X+",
        "supplied_value": "iSeq",
    }
    assert detail == expected


async def test_create_sequencing_run_under_supply_on_retry_returns_200(ctx):
    # A retry that omits a previously-set field (supplied None) is treated
    # as "caller didn't override"; the field is not compared and the
    # response is 200 with the existing idx. Matches the CLI's behaviour
    # of leaving optional flags unset on a re-run.
    instrument_run_id = unique_instrument_id("UNDERSUPPLY")
    r1 = await _post_run(
        ctx["wet"],
        ctx,
        instrument_run_id=instrument_run_id,
        platform="illumina",
        instrument_model="NovaSeq X+",
        instrument_serial="LH00123",
    )
    assert r1.status_code == 201, r1.text
    first_idx = r1.json()["sequencing_run_idx"]

    r2 = await _post_run(
        ctx["wet"],
        ctx,
        instrument_run_id=instrument_run_id,
        platform="illumina",
        # instrument_model + instrument_serial omitted → not compared.
    )
    assert r2.status_code == 200, r2.text
    assert r2.json()["sequencing_run_idx"] == first_idx

    # The stored row's optional fields are unchanged — under-supply never
    # nulls a previously-populated column.
    row = await ctx["pool"].fetchrow(
        "SELECT instrument_model, instrument_serial FROM qiita.sequencing_run WHERE idx = $1",
        first_idx,
    )
    assert dict(row) == {"instrument_model": "NovaSeq X+", "instrument_serial": "LH00123"}


# ===========================================================================
# GET /sequencing-run/{idx}
# ===========================================================================


async def _create_run(ctx, **body) -> int:
    """Create a sequencing_run via the wet_lab_admin client (tracked for
    cleanup) and return its idx."""
    body.setdefault("instrument_run_id", unique_instrument_id("GET"))
    body.setdefault("platform", "illumina")
    resp = await _post_run(ctx["wet"], ctx, **body)
    assert resp.status_code == 201, resp.text
    return resp.json()["sequencing_run_idx"]


async def test_get_sequencing_run_returns_metadata(ctx):
    # The caller-visible columns round-trip, notably instrument_model.
    idx = await _create_run(ctx, instrument_model="NovaSeq X+", instrument_serial="LH00123")
    resp = await ctx["wet"].get(f"{_ROUTE}/{idx}")
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["sequencing_run_idx"] == idx
    assert body["platform"] == "illumina"
    assert body["instrument_model"] == "NovaSeq X+"
    assert body["instrument_serial"] == "LH00123"
    assert body["retired"] is False
    assert "instrument_run_id" in body


async def test_get_sequencing_run_null_instrument_model(ctx):
    # A run with no instrument_model returns it as null (the non-bcl case the
    # CLI tolerates → QC defaults polyG OFF).
    idx = await _create_run(ctx)  # minimal: no instrument_model
    resp = await ctx["wet"].get(f"{_ROUTE}/{idx}")
    assert resp.status_code == 200, resp.text
    assert resp.json()["instrument_model"] is None


async def test_get_sequencing_run_extra_metadata_decoded(ctx):
    # JSONB is returned as a decoded object, not a JSON string.
    idx = await _create_run(ctx, extra_metadata={"flowcell": "FC-A", "lane_count": 2})
    resp = await ctx["wet"].get(f"{_ROUTE}/{idx}")
    assert resp.status_code == 200, resp.text
    assert resp.json()["extra_metadata"] == {"flowcell": "FC-A", "lane_count": 2}


async def test_get_sequencing_run_unknown_404(ctx):
    resp = await ctx["wet"].get(f"{_ROUTE}/999999999")
    assert resp.status_code == 404


async def test_get_sequencing_run_anonymous_401(ctx):
    app.state.pool = ctx["pool"]
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as anon:
        resp = await anon.get(f"{_ROUTE}/1")
    assert resp.status_code == 401


async def test_get_sequencing_run_regular_user_403(ctx):
    # The read gate requires wet_lab_admin (mirrors the pool roster route): a
    # plain user is rejected, even though a user MAY create a run.
    idx = await _create_run(ctx)
    resp = await ctx["user"].get(f"{_ROUTE}/{idx}")
    assert resp.status_code == 403


# ===========================================================================
# POST /api/v1/sequencing-run/lookup-by-instrument-run-id
# ===========================================================================


async def test_lookup_run_by_instrument_run_id_resolved_and_missing(ctx):
    """Tests the case where the lookup body mixes seeded and absent ids:
    `resolved` carries the hits keyed on instrument_run_id and `missing`
    echoes the absent value."""
    id_a = unique_instrument_id("LOOK-A")
    id_b = unique_instrument_id("LOOK-B")
    id_missing = unique_instrument_id("LOOK-MISS")
    resp_a = await _post_run(ctx["wet"], ctx, instrument_run_id=id_a, platform="illumina")
    run_a = resp_a.json()["sequencing_run_idx"]
    resp_b = await _post_run(ctx["wet"], ctx, instrument_run_id=id_b, platform="illumina")
    run_b = resp_b.json()["sequencing_run_idx"]

    resp = await ctx["wet"].post(
        URL_SEQUENCING_RUN_LOOKUP_BY_INSTRUMENT_RUN_ID,
        json={"instrument_run_ids": [id_a, id_b, id_missing]},
    )
    assert resp.status_code == 200, resp.text
    assert resp.json() == {
        "resolved": {id_a: run_a, id_b: run_b},
        "missing": [id_missing],
    }


async def test_lookup_run_by_instrument_run_id_empty_list_422(ctx):
    """Tests the case where instrument_run_ids is empty: the min_length=1
    request model rejects it at the wire boundary with 422."""
    resp = await ctx["wet"].post(
        URL_SEQUENCING_RUN_LOOKUP_BY_INSTRUMENT_RUN_ID,
        json={"instrument_run_ids": []},
    )
    assert resp.status_code == 422
