"""Integration tests for POST /api/v1/sequencing-run.

Exercises wet_lab_admin and system_admin happy paths, the role / scope
guards, regular-user role rejection, Pydantic body validation, and the
instrument_run_id uniqueness collision mapping (409 with the human-readable
detail).
"""

import json

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient

from qiita_common.auth_constants import API_PREFIX
from qiita_control_plane.main import app

from .conftest import delete_idxs, unique_instrument_id

pytestmark = pytest.mark.db


_ROUTE = f"{API_PREFIX}/sequencing-run"


# ---------------------------------------------------------------------------
# FK-reverse cleanup
# ---------------------------------------------------------------------------


async def _cleanup_tracked(pool, created: dict) -> None:
    """Drop every row tracked in `created` in FK-reverse order.

    Only sequencing_run is tracked at this layer; downstream rows
    (sequenced_pool, sequenced_sample, prep_sample, metadata) are seeded
    and torn down inside their own test files' _cleanup_tracked.
    """
    await delete_idxs(pool, "sequencing_run", created["sequencing_run"])


@pytest_asyncio.fixture
async def ctx(role_keyed_clients):
    """Per-test fixture: route-keyed AsyncClient triple plus a `created`
    tracker for FK-reverse teardown."""
    created: dict = {"sequencing_run": []}
    yield {**role_keyed_clients, "created": created}
    await _cleanup_tracked(role_keyed_clients["pool"], created)


# ---------------------------------------------------------------------------
# Route-call helper
# ---------------------------------------------------------------------------


async def _post_run(client, ctx, **body):
    """POST the route and, on 201, track the created sequencing_run idx for
    FK-reverse cleanup."""
    resp = await client.post(_ROUTE, json=body)
    if resp.status_code == 201:
        ctx["created"]["sequencing_run"].append(resp.json()["sequencing_run_idx"])
    return resp


# ===========================================================================
# Happy paths
# ===========================================================================


async def test_create_sequencing_run_wet_lab_admin_minimal(ctx):
    # Wet_lab_admin caller posts the minimum-required body; the route
    # mints a sequencing_run row and returns its idx.
    resp = await _post_run(
        ctx["wet"],
        ctx,
        instrument_run_id=unique_instrument_id("WET"),
        platform="illumina",
    )
    assert resp.status_code == 201, resp.text
    rj = resp.json()
    expected = {
        # Auto-generated by the DB; copy actual into expected so the
        # equality confirms field presence without pinning the idx value.
        "sequencing_run_idx": rj["sequencing_run_idx"],
    }
    assert rj == expected

    # Verify the row landed with the caller's principal_idx as creator and
    # the platform persisted as the enum value.
    row = await ctx["pool"].fetchrow(
        "SELECT instrument_run_id, platform, created_by_idx,"
        " instrument_model, instrument_serial, run_performed_at, extra_metadata"
        " FROM qiita.sequencing_run WHERE idx = $1",
        rj["sequencing_run_idx"],
    )
    actual = dict(row)
    expected = {
        # Auto-generated by the test helper; copy actual into expected so
        # the equality confirms field presence without pinning the value.
        "instrument_run_id": actual["instrument_run_id"],
        "platform": "illumina",
        "created_by_idx": ctx["wet_session"]["principal_idx"],
        "instrument_model": None,
        "instrument_serial": None,
        "run_performed_at": None,
        "extra_metadata": None,
    }
    assert actual == expected


async def test_create_sequencing_run_system_admin_all_fields(ctx):
    # System_admin caller posts every settable column; the route persists
    # all of them.
    instrument_run_id = unique_instrument_id("ADM")
    resp = await _post_run(
        ctx["admin"],
        ctx,
        instrument_run_id=instrument_run_id,
        platform="pacbio_smrt",
        instrument_model="NovaSeq X+",
        instrument_serial="LH00123",
        run_performed_at="2026-04-01T12:00:00Z",
        extra_metadata={"lane_count": 2, "flowcell": "FC-A"},
    )
    assert resp.status_code == 201, resp.text

    row = await ctx["pool"].fetchrow(
        "SELECT instrument_run_id, platform, instrument_model, instrument_serial,"
        " run_performed_at, extra_metadata"
        " FROM qiita.sequencing_run WHERE idx = $1",
        resp.json()["sequencing_run_idx"],
    )
    # asyncpg returns JSONB as a JSON string by default; decode in-place so
    # the dict equality compares structured payloads.
    actual = dict(row)
    actual["extra_metadata"] = json.loads(actual["extra_metadata"])
    expected = {
        "instrument_run_id": instrument_run_id,
        "platform": "pacbio_smrt",
        "instrument_model": "NovaSeq X+",
        "instrument_serial": "LH00123",
        # TIMESTAMPTZ comes back as a tz-aware datetime; copy actual since
        # this assertion only verifies the column was populated.
        "run_performed_at": actual["run_performed_at"],
        "extra_metadata": {"flowcell": "FC-A", "lane_count": 2},
    }
    assert actual == expected


# ===========================================================================
# Auth / scope / role guards
# ===========================================================================


async def test_create_sequencing_run_anonymous_401(ctx):
    # No Authorization header → require_complete_profile chain raises 401.
    app.state.pool = ctx["pool"]
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as anon:
        resp = await anon.post(
            _ROUTE,
            json={
                "instrument_run_id": unique_instrument_id("ANON"),
                "platform": "illumina",
            },
        )
    assert resp.status_code == 401


async def test_create_sequencing_run_missing_scope_403(ctx, no_prep_sample_write_client):
    # PAT omits Scope.PREP_SAMPLE_WRITE → require_scope rejects 403 before
    # the role check runs.
    resp = await no_prep_sample_write_client.post(
        _ROUTE,
        json={
            "instrument_run_id": unique_instrument_id("NOSCOPE"),
            "platform": "illumina",
        },
    )
    assert resp.status_code == 403
    assert "prep_sample:write" in resp.json()["detail"]


async def test_create_sequencing_run_regular_user_role_403(
    ctx, regular_user_with_prep_sample_write_client
):
    # Regular user (system_role=user) holding an explicit
    # PREP_SAMPLE_WRITE-bearing PAT: require_scope passes, but
    # require_role_at_least(WET_LAB_ADMIN) rejects with 403. The user's
    # session-fixture token does not carry PREP_SAMPLE_WRITE (the USER
    # role ceiling excludes it), so this fixture mints a PAT directly to
    # exercise the role gate independently of the scope gate.
    resp = await regular_user_with_prep_sample_write_client.post(
        _ROUTE,
        json={
            "instrument_run_id": unique_instrument_id("USER"),
            "platform": "illumina",
        },
    )
    assert resp.status_code == 403
    assert "wet_lab_admin" in resp.json()["detail"]


# ===========================================================================
# Body validation
# ===========================================================================


async def test_create_sequencing_run_missing_required_field_422(ctx):
    # Pydantic validation rejects {} because instrument_run_id and platform
    # are both required.
    resp = await ctx["wet"].post(_ROUTE, json={})
    assert resp.status_code == 422
    missing_locs = {tuple(err["loc"]) for err in resp.json()["detail"]}
    assert ("body", "instrument_run_id") in missing_locs
    assert ("body", "platform") in missing_locs


async def test_create_sequencing_run_invalid_platform_422(ctx):
    # The Platform StrEnum rejects values outside the closed set.
    resp = await ctx["wet"].post(
        _ROUTE,
        json={
            "instrument_run_id": unique_instrument_id("BADP"),
            "platform": "nanopore",
        },
    )
    assert resp.status_code == 422


async def test_create_sequencing_run_empty_instrument_run_id_422(ctx):
    # Pydantic min_length=1 rejects an empty string.
    resp = await ctx["wet"].post(
        _ROUTE,
        json={"instrument_run_id": "", "platform": "illumina"},
    )
    assert resp.status_code == 422


async def test_create_sequencing_run_extra_field_422(ctx):
    # The request model carries extra="forbid"; an unknown field is rejected
    # at the Pydantic boundary rather than silently dropped.
    resp = await ctx["wet"].post(
        _ROUTE,
        json={
            "instrument_run_id": unique_instrument_id("XTRA"),
            "platform": "illumina",
            "not_a_real_column": "x",
        },
    )
    assert resp.status_code == 422


# ===========================================================================
# Constraint mapping
# ===========================================================================


async def test_create_sequencing_run_duplicate_instrument_run_id_409(ctx):
    # First POST claims an instrument_run_id; a second POST with the same id
    # trips sequencing_run_instrument_run_id_unique and the route maps it
    # to 409 with the human-readable message from the mapping dict.
    instrument_run_id = unique_instrument_id("DUP")
    r1 = await _post_run(
        ctx["wet"],
        ctx,
        instrument_run_id=instrument_run_id,
        platform="illumina",
    )
    assert r1.status_code == 201, r1.text

    r2 = await _post_run(
        ctx["wet"],
        ctx,
        instrument_run_id=instrument_run_id,
        platform="illumina",
    )
    assert r2.status_code == 409
    assert r2.json()["detail"] == "instrument_run_id already in use"
