"""Shared Pydantic models: work ticket states, API schemas, identifier types.

This package is the CP↔CO contract layer. It was split out of a single
`models.py` module into domain submodules; this `__init__` re-exports every
public name so `from qiita_common.models import X` keeps working unchanged for
every symbol that used to live in the flat module. The frequently-imported
standard-library / pydantic / auth-constant names are re-exported too, so
existing `from qiita_common.models import BaseModel` (etc.) callers keep working.
"""

from datetime import date
from decimal import Decimal
from enum import StrEnum
from typing import Annotated, Any, ClassVar, Literal
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    computed_field,
    field_validator,
    model_validator,
)
from pydantic.types import Base64Bytes

from qiita_common.auth_constants import (
    MAX_NAME_LENGTH,
    MAX_TABLE_NAME_LENGTH,
    MAX_VERSION_LENGTH,
    PAT_MAX_TTL_DAYS,
    SERVICE_TOKEN_MAX_TTL_DAYS,
    SystemRole,
)
from qiita_common.models._base import (
    BlockScopeTarget,
    ComputeTarget,
    PatchRequestModel,
    PrepSampleScopeTarget,
    ReferenceScopeTarget,
    ScopeTarget,
    ScopeTargetKind,
    SequencedPoolScopeTarget,
    StepStatus,
    StudyPrepScopeTarget,
    check_derived_inputs,
    check_exactly_one_runtime,
)
from qiita_common.models.auth import (
    ApiTokenMintRequest,
    ApiTokenMintResponse,
    ApiTokenSummary,
    AuthEventResponse,
    CliLoginExchangeRequest,
    PrepSampleRetiredUpdate,
    PrincipalDisabledUpdate,
    PrincipalRetiredUpdate,
    PrincipalSystemRoleUpdate,
    RevokeAllTokensResponse,
    ServiceAccountCreate,
    ServiceAccountCreateResponse,
    WhoAmIAnonymousResponse,
    WhoAmIHumanResponse,
    WhoAmIResponse,
    WhoAmIServiceResponse,
)
from qiita_common.models.biosample import (
    BIOSAMPLE_FIELD_HOST_TAXON_ID,
    BIOSAMPLE_FIELD_TAXON_ID,
    MATRIX_TUBE_ID_PATTERN,
    MISSING_REASON_CONTROL_SAMPLE,
    MISSING_REASON_NOT_APPLICABLE,
    MISSING_REASON_VALUE_COLUMN,
    NCBI_TAXONOMY_HUMAN_TERM_ID,
    NCBI_TAXONOMY_NAME,
    TERMINOLOGY_TERM_VALUE_COLUMN,
    BiosampleAccessionField,
    BiosampleImportRequest,
    BiosampleImportResponse,
    BiosampleLookupByAccessionRequest,
    BiosampleLookupByAccessionResponse,
    BiosampleLookupByMatrixTubeIdRequest,
    BiosampleLookupByMatrixTubeIdResponse,
    BiosamplePatchRequest,
    BiosampleResponse,
    GlobalMetadataEntry,
    IdxsListResponse,
    MetadataChecklistRef,
    MissingReasonRef,
    OwnerBiosampleIdExportResponse,
    OwnerBiosampleIdRow,
    SequencedSampleListItem,
    SequencedSampleListResponse,
    StudyAccessionField,
    StudyListItem,
    StudyListResponse,
    StudyLookupByAccessionRequest,
    StudyLookupByAccessionResponse,
    TerminologyTermRef,
)
from qiita_common.models.ena import (
    EnaRunRecord,
    EnaSampleAttributes,
    EnaStudyHeader,
    ResolverKind,
    SourceArchive,
)
from qiita_common.models.health import HealthResponse, HealthStatus
from qiita_common.models.host_filter_profile import (
    HostFilterOutcome,
    HostFilterProfile,
    HostFilterResolution,
)
from qiita_common.models.reference import (
    HOST_FILTER_INDEX_TYPE_MINIMAP2,
    HOST_FILTER_INDEX_TYPE_RYPE,
    HOST_FILTER_REQUIRED_INDEX_TYPES,
    INDEX_TYPE_BOWTIE2,
    INDEX_TYPE_MINIMAP2,
    INDEX_TYPE_RYPE_ROUTER,
    READ_MASK_BUCKET,
    VALID_STATUS_TRANSITIONS,
    FeatureHashEntry,
    FieldDataType,
    GenomeSource,
    Platform,
    PrepProtocolResponse,
    ReadMaskBucket,
    ReadMaskReason,
    ReferenceArtifactPurgeResponse,
    ReferenceCreateRequest,
    ReferenceDeleteResponse,
    ReferenceIndex,
    ReferenceKind,
    ReferenceResponse,
    ReferenceShardIndexStatus,
    ReferenceStatus,
    ReferenceStatusUpdate,
    TerminologyStatus,
    TerminologyTermObsoletionKind,
    Tier,
    read_mask_reason_sql_list,
)
from qiita_common.models.sequencing import (
    AlignmentDefinitionDeleteResponse,
    MaskDefinition,
    MaskDefinitionDeleteResponse,
    MaskDefinitionMintRequest,
    MaskedReadExportManifest,
    MaskedReadExportSample,
    MaskedReadExportTicketRequest,
    MateQCAggregate,
    MergedQCAggregate,
    PointQCAggregate,
    PoolCompletionStatus,
    PoolQCReport,
    PoolReadMetrics,
    ReadMaskedDoGetTicketRequest,
    SampleQCReport,
    SequencedPoolCreateRequest,
    SequencedPoolCreateResponse,
    SequencedPoolDeleteResponse,
    SequencedPoolPreflightResponse,
    SequencedPoolPreflightUpdateLaneRequest,
    SequencedPoolPreflightUpdateLaneResponse,
    SequencedPoolResponse,
    SequencedSampleCreateRequest,
    SequencedSampleCreateResponse,
    SequencedSamplePatchRequest,
    SequencedSampleResponse,
    SequenceRange,
    SequenceRangeMintRequest,
    SequencingRunCreateRequest,
    SequencingRunCreateResponse,
    SequencingRunLookupByInstrumentRunIdRequest,
    SequencingRunLookupByInstrumentRunIdResponse,
    SequencingRunResponse,
    merge_qc_reports,
)
from qiita_common.models.step import (
    AlignmentDoGetTicketRequest,
    DoGetTicketRequest,
    DoGetTicketResponse,
    FoundJobWire,
    StepBaselineResources,
    StepFindByNameRequest,
    StepFindByNameResponse,
    StepHandleWire,
    StepPlanRequest,
    StepPlanResponse,
    StepResultRequest,
    StepResultResponse,
    StepStatusRequest,
    StepStatusWire,
    StepSubmitRequest,
)
from qiita_common.models.study import StudyCreate, StudyPatchRequest, StudyResponse
from qiita_common.models.upload import (
    EmailReceiptStatus,
    UploadCreateRequest,
    UploadCreateResponse,
    UploadDoneRequest,
    UploadResponse,
    UploadStatus,
)
from qiita_common.models.user import ORCID_PATTERN, UserCreate, UserResponse, UserUpdate
from qiita_common.models.work_ticket import (
    NON_TERMINAL_WORK_TICKET_STATES,
    TERMINAL_WORK_TICKET_STATES,
    AlignPlanBlock,
    AlignPlanPartition,
    AlignPlanRequest,
    AlignPlanResponse,
    BlockMaskPlanRequest,
    BlockMaskPlanResponse,
    BlockPlanBlock,
    BlockPlanPartition,
    FailureType,
    ProcessingKind,
    ResourceOverride,
    StepProgressState,
    StepType,
    WorkTicket,
    WorkTicketCreateRequest,
    WorkTicketFailureStage,
    WorkTicketResponse,
    WorkTicketState,
    WorkTicketStepLogs,
    WorkTicketSummary,
)

__all__ = [
    # Re-exported standard-library / pydantic / auth-constant names, preserved
    # so `from qiita_common.models import <name>` keeps working for the symbols
    # the flat module happened to expose.
    "Annotated",
    "Any",
    "AwareDatetime",
    "Base64Bytes",
    "BaseModel",
    "ClassVar",
    "ConfigDict",
    "Decimal",
    "EmailStr",
    "Field",
    "Literal",
    "StrEnum",
    "UUID",
    "computed_field",
    "date",
    "field_validator",
    "model_validator",
    "MAX_NAME_LENGTH",
    "MAX_TABLE_NAME_LENGTH",
    "MAX_VERSION_LENGTH",
    "PAT_MAX_TTL_DAYS",
    "SERVICE_TOKEN_MAX_TTL_DAYS",
    "SystemRole",
    # Module-level constants.
    "BIOSAMPLE_FIELD_HOST_TAXON_ID",
    "BIOSAMPLE_FIELD_TAXON_ID",
    "HOST_FILTER_INDEX_TYPE_MINIMAP2",
    "HOST_FILTER_INDEX_TYPE_RYPE",
    "HOST_FILTER_REQUIRED_INDEX_TYPES",
    "INDEX_TYPE_BOWTIE2",
    "INDEX_TYPE_MINIMAP2",
    "INDEX_TYPE_RYPE_ROUTER",
    "MATRIX_TUBE_ID_PATTERN",
    "MISSING_REASON_CONTROL_SAMPLE",
    "MISSING_REASON_NOT_APPLICABLE",
    "MISSING_REASON_VALUE_COLUMN",
    "NCBI_TAXONOMY_HUMAN_TERM_ID",
    "NCBI_TAXONOMY_NAME",
    "ORCID_PATTERN",
    "TERMINOLOGY_TERM_VALUE_COLUMN",
    "VALID_STATUS_TRANSITIONS",
    # Shared base types.
    "BlockScopeTarget",
    "ComputeTarget",
    "PatchRequestModel",
    "PrepSampleScopeTarget",
    "ReferenceScopeTarget",
    "ScopeTarget",
    "ScopeTargetKind",
    "SequencedPoolScopeTarget",
    "StepStatus",
    "StudyPrepScopeTarget",
    "check_derived_inputs",
    "check_exactly_one_runtime",
    # Health.
    "HealthResponse",
    "HealthStatus",
    # Host filter.
    "HostFilterOutcome",
    "HostFilterProfile",
    "HostFilterResolution",
    # Reference.
    "FeatureHashEntry",
    "FieldDataType",
    "GenomeSource",
    "Platform",
    "PrepProtocolResponse",
    "READ_MASK_BUCKET",
    "ReadMaskBucket",
    "ReadMaskReason",
    "read_mask_reason_sql_list",
    "ReferenceArtifactPurgeResponse",
    "ReferenceCreateRequest",
    "ReferenceDeleteResponse",
    "ReferenceIndex",
    "ReferenceKind",
    "ReferenceResponse",
    "ReferenceShardIndexStatus",
    "ReferenceStatus",
    "ReferenceStatusUpdate",
    "TerminologyStatus",
    "TerminologyTermObsoletionKind",
    "Tier",
    # Step wire contract.
    "AlignmentDoGetTicketRequest",
    "DoGetTicketRequest",
    "DoGetTicketResponse",
    "FoundJobWire",
    "StepBaselineResources",
    "StepFindByNameRequest",
    "StepFindByNameResponse",
    "StepHandleWire",
    "StepPlanRequest",
    "StepPlanResponse",
    "StepResultRequest",
    "StepResultResponse",
    "StepStatusRequest",
    "StepStatusWire",
    "StepSubmitRequest",
    # Upload.
    "EmailReceiptStatus",
    "UploadCreateRequest",
    "UploadCreateResponse",
    "UploadDoneRequest",
    "UploadResponse",
    "UploadStatus",
    # User.
    "UserCreate",
    "UserResponse",
    "UserUpdate",
    # Biosample.
    "BiosampleAccessionField",
    "BiosampleImportRequest",
    "BiosampleImportResponse",
    "BiosampleLookupByAccessionRequest",
    "BiosampleLookupByAccessionResponse",
    "BiosampleLookupByMatrixTubeIdRequest",
    "BiosampleLookupByMatrixTubeIdResponse",
    "BiosamplePatchRequest",
    "BiosampleResponse",
    "GlobalMetadataEntry",
    "IdxsListResponse",
    "MetadataChecklistRef",
    "MissingReasonRef",
    "OwnerBiosampleIdExportResponse",
    "OwnerBiosampleIdRow",
    "SequencedSampleListItem",
    "SequencedSampleListResponse",
    "StudyAccessionField",
    "StudyListItem",
    "StudyListResponse",
    "StudyLookupByAccessionRequest",
    "StudyLookupByAccessionResponse",
    "TerminologyTermRef",
    # ENA/SRA metadata.
    "EnaRunRecord",
    "EnaSampleAttributes",
    "EnaStudyHeader",
    "ResolverKind",
    "SourceArchive",
    # Study.
    "StudyCreate",
    "StudyPatchRequest",
    "StudyResponse",
    # Auth.
    "ApiTokenMintRequest",
    "ApiTokenMintResponse",
    "ApiTokenSummary",
    "AuthEventResponse",
    "CliLoginExchangeRequest",
    "PrepSampleRetiredUpdate",
    "PrincipalDisabledUpdate",
    "PrincipalRetiredUpdate",
    "PrincipalSystemRoleUpdate",
    "RevokeAllTokensResponse",
    "ServiceAccountCreate",
    "ServiceAccountCreateResponse",
    "WhoAmIAnonymousResponse",
    "WhoAmIHumanResponse",
    "WhoAmIResponse",
    "WhoAmIServiceResponse",
    # Work tickets / actions.
    "NON_TERMINAL_WORK_TICKET_STATES",
    "TERMINAL_WORK_TICKET_STATES",
    "FailureType",
    "ProcessingKind",
    "ResourceOverride",
    "StepProgressState",
    "StepType",
    "WorkTicket",
    "WorkTicketCreateRequest",
    "WorkTicketFailureStage",
    "WorkTicketResponse",
    "WorkTicketState",
    "WorkTicketStepLogs",
    "WorkTicketSummary",
    # Block mask plan.
    "BlockMaskPlanRequest",
    "BlockMaskPlanResponse",
    "BlockPlanBlock",
    "BlockPlanPartition",
    # Align plan.
    "AlignPlanBlock",
    "AlignPlanPartition",
    "AlignPlanRequest",
    "AlignPlanResponse",
    # Sequencing-run / sequenced-pool / sequenced-sample.
    "AlignmentDefinitionDeleteResponse",
    "MaskDefinition",
    "MaskDefinitionDeleteResponse",
    "MaskDefinitionMintRequest",
    "MaskedReadExportManifest",
    "MaskedReadExportSample",
    "MaskedReadExportTicketRequest",
    "MateQCAggregate",
    "MergedQCAggregate",
    "PointQCAggregate",
    "PoolCompletionStatus",
    "PoolQCReport",
    "PoolReadMetrics",
    "ReadMaskedDoGetTicketRequest",
    "SampleQCReport",
    "SequenceRange",
    "SequenceRangeMintRequest",
    "SequencedPoolCreateRequest",
    "SequencedPoolCreateResponse",
    "SequencedPoolDeleteResponse",
    "SequencedPoolPreflightResponse",
    "SequencedPoolPreflightUpdateLaneRequest",
    "SequencedPoolPreflightUpdateLaneResponse",
    "SequencedPoolResponse",
    "SequencedSampleCreateRequest",
    "SequencedSampleCreateResponse",
    "SequencedSamplePatchRequest",
    "SequencedSampleResponse",
    "SequencingRunCreateRequest",
    "SequencingRunCreateResponse",
    "SequencingRunLookupByInstrumentRunIdRequest",
    "SequencingRunLookupByInstrumentRunIdResponse",
    "SequencingRunResponse",
    "merge_qc_reports",
]
